language: c
dist: trusty
sudo: true

matrix:
  include:
  # - os: linux
  #   compiler: gcc
  # - os: linux
  #   compiler: gcc
  #   env: 
  #     - CC_OQS=gcc-4.9
  #     - ENABLE_SIDH_IQC_REF=1
  #   addons:
  #     apt:
  #       sources:
  #       - ubuntu-toolchain-r-test
  #       packages:
  #       - gcc-4.9
  # - os: linux
  #   compiler: gcc
  #   env: CC_OQS=gcc-5
  #   addons:
  #     apt:
  #       sources:
  #       - ubuntu-toolchain-r-test
  #       packages:
  #       - gcc-5
  - os: linux
    compiler: gcc
    env: 
    - CC_OQS=gcc-6 
    - USE_OPENSSL=1 
    - ENABLE_CODE_MCBITS=1 
    - ENABLE_SIDH_IQC_REF=1
    - LCOV=1
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-6
        - libssl-dev
    before_install:
    - sh .travis/install-libsodium.sh
    - sh .travis/install-lcov-linux.sh;
  # - os: osx
  #   compiler: clang
  #   env: CC_OQS=clang
  # - os: osx
  #   compiler: clang
  #   env: 
  #   - CC_OQS=clang 
  #   - AES_NI=0 
  #   - USE_OPENSSL=1 
  #   - OPENSSL_DIR=/usr/local/opt/openssl # openssl is a keg-only package
  #   - ENABLE_CODE_MCBITS=1 
  #   - ENABLE_SIDH_IQC_REF=1
  #   before_install:
  #   - sh .travis/install-libsodium.sh

install:
  - sh .travis/install-clang-format.sh

script:
  - ./.travis-tests.sh

after_success:
  - if [[ $LCOV == 1 ]]; lcov -d . -b . --capture --output-file coverage.info; coveralls-lcov coverage.info; fi;
